services:
  redis:
    image: redis:7
    ports:
      - '6379:6379'

  # chroma:
  #   image: chromadb/chroma:latest
  #   volumes:
  #     - ./chroma-data:/chroma/chroma
  #   ports:
  #     - '8000:8000'

  chatbot-api:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - redis
      # - chroma
    environment:
      - REDIS_HOST=redis
      # - CHROMA_HOST=http://host.docker.internal:8000
      - OLLAMA_HOST=http://host.docker.internal:11434
