services:
  redis:
    image: redis:7
    ports:
      - '6379:6379'

  chatbot-api:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - OLLAMA_HOST=https://ollama.walrus-labs.fr
